version: "3.5"

services:
  postgres:
    container_name: postgres-crawl
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5436:5432"

volumes:
  postgres-db:
    driver: local
